services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-sb-estudos
    restart: always
    environment:
      - MYSQL_DATABASE=meu_projeto_spring
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: