spring.application.name=spring-studies

# 1 - username do banco
spring.datasource.username=admin

# 2 - senha do usuario do banco
spring.datasource.password=12345

# 3 - url do banco de dados
spring.datasource.url=jdbc:h2:file:./db_auth

# 4 - "dialeto" do banco
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# 5 - Configs h2
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true